version: "3.7"
services:
  db:
    image: postgres:11.5
    environment:
      - POSTGRES_USER=testing
      - POSTGRES_PASSWORD=testing
      - POSTGRES_DB=testing
    ports:
      - "54320:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data: ~